### PR TITLE
New groundnet for KRIC

### PR DESCRIPTION
**Pull request by Portree-Kid**
A new groundnet has been submitted by varjat@gmail.com.

### CODE REVIEW

**Comment by BecOzIcan** [comment]
Already merged as #880

**Comment by wkitty42** [comment]
that's weird... how could this submission have been doubled up into two submissions like that? just simply by clicking twice on the submit button? perhaps some hash of the file(s) could be kept for the ICAO and compared in the client to prevent this from happening?? if the hash is the same, display a note to the user and do not submit... if the hash is different, submit as normally done...

**Comment by Portree-Kid** [comment]
I have put in multiple safeguards and there seems to be cases where it
escapes. It's not really that critical as the number of submissions are
pretty low.

**Comment by wkitty42** [comment]
ok , no problem... i was just thinking about using hashes for something else and this is another problem where they can be handy... anyway, since this issue is closed, i'll hush now :wink:

**Pull request closed without merging**
