### PR TITLE
New threshold for KPHX

### PR DESCRIPTION
**Pull request by Portree-Kid**
A new threshold has been submitted by pilot.honu4@gmail.com.

### CODE REVIEW

**Comment by BecOzIcan** [comment]
Is this an intended change. Can't figure out why 07R/25L would be renamed to "NaN"

**Comment by Honu4** [comment]
> Is this an intended change. Can't figure out why 07R/25L would be renamed to "NaN"

I've noticed this happens when there is a xxL/xxR. the threshold name changes to "NaN" and I can't change it back. If there is no L/R it seems okay.

FGA v.0.0.34, MacOS

**Comment by BecOzIcan** [comment]
Thanks for clarifying D, will put that on potential FGA Bugs. 
Cheers
Ian

**Comment by Portree-Kid** [comment]
It's a bug in FGA please open a ticket there.

**Comment by BecOzIcan** [comment]
Raised as FGA Bug

https://github.com/Portree-Kid/flightgear-airports/issues/147

**Pull request closed without merging**
