### PR TITLE
LIMJ_1610885440040

### PR DESCRIPTION
**Pull request by Portree-Kid**
Submitted by sfrsfr@gmail.com

### CODE REVIEW

**Comment by sfrsfrsfr** [comment]
Source: openstreetmap

**Comment by BecOzIcan** [comment]
@Portree-Kid please refer to my email dated 10APR20 wrt Terrasync integration. 

I can't spend any reviewing/merging files in /Airport/I/C/A/O which are not directly required by AI traffic ie ILS or TWR which are scenery related.
I am happy to deal with groundnet and threshold files still.

**Comment by sfrsfrsfr** [comment]
@BecOzIcan understood. i'll refrain from submitting any non-AI related fixes until this is sorted out or an alternative is found.
thx for your efforts!

**Comment by BecOzIcan** [comment]
Thanks for understanding, I can handle one here and there but don't want to open a can of worms.

**Pull request merged**
