### PR TITLE
New threshold for EDDE

### PR DESCRIPTION
**Pull request by Portree-Kid**
A new threshold has been submitted by sfrsfr@gmail.com.

### CODE REVIEW

**Comment by sfrsfrsfr** [comment]
ps reject/discard. i only took the fg airport layout as a reference.
the original threshold is fine as it it.

**Comment by sfrsfrsfr** [comment]
this is basically the original threshold.

**Comment by sfrsfrsfr** [comment]
as it seem to have failed due to KHWD: its groundnet is _very_ broken/basic. i might work on it this weekend.

**Comment by BecOzIcan** [comment]
See previous commit. Values should be 

10
50.981279
10.939733

28
50.978580
10.973493

**Pull request closed without merging**
