### PR TITLE
KCHS_1594837229234

### PR DESCRIPTION
**Pull request by Portree-Kid**
Submitted by wkitty42@gmail.com

### CODE REVIEW

**Comment by BecOzIcan** [comment]
Invalid Pushbacks Result in Departing aircrafts loosing their anchor to the taxiways and making their own path to threshold
Pushback Holding point should not be part of the taxiway segments (but can overlap it on their own separate route) 
image

image

Invalid Flow for arrivals on RWY15
Exit route is ahead of touchdown point. Aircrafts have no exit route. Use 03 to backtrack and bump into departing aircrafts heading for THR15
image

image

**Comment by wkitty42** [comment]
wow! really? geez... i'll take a look... tomorrow most likely :cat2: 

i don't understand how the pushback holding point should not be part of the taxiway... don't the pushbacks have to connect to the taxiway? isn't that a/the holding point?

**Comment by wkitty42** [comment]
> Invalid Pushbacks Result in Departing aircrafts loosing their anchor to the taxiways and making their own path to threshold
> Pushback Holding point should not be part of the taxiway segments (but can overlap it on their own separate route)
> image

@BecOzIcan  are you saying the pink line should go past the taxiway path and then hook back and connect to it?
or just move the push back holding point to just before the taxiway path? i need some pictures :joy_cat:

**Comment by BecOzIcan** [comment]
I am not sure how many (more) times I can ask you to read the wiki and test your groundnet.
http://wiki.flightgear.org/AI_Traffic

"For the same reason the Pushback Holding point should NOT be directly placed on the taxiway as shown in the image on the right 'On Taxiway Pushback Holding Point in Taxidraw'. Using this particular configuration, once the aircraft 'cleared for taxi', it will ignore the taxiway segments on its left and right and keep its heading, rolling forward towards the original parking position, then 'get lost' and start spinning around"

**Comment by wkitty42** [comment]
On 7/16/20 9:23 AM, Yves Tolosa-Joas wrote:
> I am not sure how many (more) times I can ask you to read the wiki and test your 
> groundnet.
> http://wiki.flightgear.org/AI_Traffic


dude, please... i'm 50+ and been doing FG for what? 6 years now? i know about 
the wiki and i have read it... numerous times... that particular page? probably 
over 100 times but anyway...

thanks for all the editing you've done on that page, BTW :)

> "For the same reason the Pushback Holding point should NOT be directly placed on 
> the taxiway as shown in the image on the right 'On Taxiway Pushback Holding 
> Point in Taxidraw'. Using this particular configuration, once the aircraft 
> 'cleared for taxi', it will ignore the taxiway segments on its left and right 
> and keep its heading, rolling forward towards the original parking position, 
> then 'get lost' and start spinning around"


i've read that over and over... the picture doesn't make sense to me... i'm 
/not/ using taxidraw... at all... only FGA...

it really sounds like i do need that extra pushback path ""hook"" going past my 
taxiways and then back to the taxiway... my question then is where do i put the 
FGA PushBack marker? on the taxiway connection or on the "hook"?

**Comment by BecOzIcan** [comment]
Nice try 😀 I am 55 and have done fg for 8 years only.
Yes. Draw a single final pushback segment passed the taxiway and finish it with the pushback holding point

**Pull request closed without merging**
