### PR TITLE
New threshold for NCMR

### PR DESCRIPTION
**Pull request by Portree-Kid**
A new threshold has been submitted by legoboyvdlp@gmail.com.

### CODE REVIEW

**Comment by BecOzIcan** [comment]
Data not consistent with Published AIP
https://www.transport.gov.ck/wp-content/uploads/2022/01/aip_cookislands_master_12aug21_bkmk.pdf
image

Expected THR Values
THR09 : -19.840981, -157.708717
THR27 -19.844228, -157.697783

Data in PR places the THR off runway 

image

**Comment by legoboyvdlp** [comment]
Instead of using satellite imagery, it would be preferable to use FlightGear for validation -- as therefore you would have seen that currently, FlightGear starts up approximately 200 metres away from the actual position of the runway. My coordinates are correct, and match the scenery exactly.


image

**Comment by BecOzIcan** [comment]
I see your point. Your coordinates are consistent with current (erroneous) scenery. Nevertheless they will becomes obsolete as soon as the next WED contributor corrects the airport layout.

Let s stick to real world data especially when publicly available so we all improve the quality of the simulation and reduce the noise around the overall scenery quality and misplaced runways.

**Comment by BecOzIcan** [comment]
Crossed message sorry. Easy enough in WED there is a marker to set the threshold with lat lon 
image

and then you simply enter the size of the blastpad (yellow box here) in the runway definition, to extend the runway to its physical end 

image

**Pull request closed without merging**
