### PR TITLE
EDDK_1610829395489

### LINKED ISSUE #424: EDDK Tower position incorrect
https://sourceforge.net/p/flightgear/codetickets/1795/

> Confirmed. Tower location should be closer to 7.134279 50.869092

### PR DESCRIPTION
**Pull request by Portree-Kid**
Submitted by sfrsfr@gmail.com

### CODE REVIEW

**Comment by sfrsfrsfr** [comment]
Fixes #424

**Comment by sfrsfrsfr** [comment]
i uploaded a corrected EDDK.twr.xml not a groundnet. Shouldn't it check what i uploaded instead?

**Comment by BecOzIcan** [comment]
There is no automatic validation of TWR data. 

Please confirm data source; Not coordinates found at
https://aip.dfs.de/basicIFR/2020DEC31/d7f72747b57b648c19f079d387351000.html

**Comment by sfrsfrsfr** [comment]
The data source is Openstreetmap or any other map service for that matter.

**Comment by BecOzIcan** [comment]
image

**Pull request merged**
