### PR TITLE
KCLT_1594836923614

### PR DESCRIPTION
**Pull request by Portree-Kid**
Submitted by wkitty42@gmail.com

### CODE REVIEW

**Comment by wkitty42** [comment]
yeah, i need this travis error explained to me, please... i thought i had figured out it was saying that indexes 21 and 23 were radius colliding but apparently i didn't read it correctly?

**Comment by Portree-Kid** [comment]
Yes actually that's what it means "Radius of 21 & 23 intersect" but of course it still doesn't have the "boxes"

**Comment by wkitty42** [comment]
ok and the numbers are the index numbers inside the xml file, right? so index 21 and index 23?

if that's positive, then i did do it properly by adjusting gate A11 (21) and gate A13 (23)... i guess i need to move them some more...

when you say it still doesn't have the "boxes" are you saying that travis is checking using the circles instead of the "house"?

**Comment by wkitty42** [comment]
delete this one, please...

**Pull request closed without merging**
