### PR TITLE
New groundnet for OIIE

### PR DESCRIPTION
**Pull request by Portree-Kid**
A new groundnet has been submitted by farisyodude@outlook.com.

### CODE REVIEW

**Comment by BecOzIcan** [comment]
Not a valid Groundnet. Incomplete taxiway circuits. Parkings not connected

**Comment by UmKhammas9** [comment]
how to fix

**Comment by BecOzIcan** [comment]
Start here 
https://wiki.flightgear.org/AI_Traffic

**Comment by UmKhammas9** [comment]
ok what do i do wrong because i connected them to the runways

**Comment by UmKhammas9** [comment]
is this what i am suppose to do

**Comment by BecOzIcan** [comment]
Your parkings are not connected. Should you run the check tool fg airport will show you each problematic node

**Comment by UmKhammas9** [comment]
where

**Pull request closed without merging**
