### PR TITLE
KCLT_1594849022131

### PR DESCRIPTION
**Pull request by Portree-Kid**
Submitted by wkitty42@gmail.com

### CODE REVIEW

**Comment by wkitty42** [comment]
YAY!! merge this one! LOL

**Comment by BecOzIcan** [comment]
Invalid Pushbacks. Holding point should not be part of the taxiway. 
Refer to http://wiki.flightgear.org/AI_Traffic

**Comment by wkitty42** [comment]
i don't understand what you mean... where is a hold point supposed to be if not at the end of the taxiway? it is the last point before the "on runway" markers, right?

can you point to a more specific section of the wiki article, please? maybe also show or tell me where you see the problem in the groundnet? FGA 0.0.22 won't check and 0.0.21 says everything is ok...

i may also have already handled this... i do remember going back and adding the "on runway" markers but may not have uploaded that one, yet...

**Comment by BecOzIcan** [comment]
Sorry for the confusion, I meant Pushback Holding Point. Same as with your other submission, the last segment in the pushback route must be off the taxiway. You would have seen when testing KCLT how aircrafts try to return to the gate once pushback complete (instead of starting rolling on the taxiway)

**Comment by BecOzIcan** [comment]
Also, aircrafts do not seem to have routes IN the parking positions ? They need to go all the way to the pushback holding point and then track back to the parking ? 

image

**Comment by wkitty42** [comment]
ahhhh, ok... i'll work on that... on one of the other groundnets i've placed  one way paths into parking and then the pushback comes out another way... haven't seen any others doing that but it seems to work ok...

**Pull request closed without merging**
