### PR TITLE
New threshold for NCRG

### PR DESCRIPTION
**Pull request by Portree-Kid**
A new threshold has been submitted by legoboyvdlp@gmail.com.

### CODE REVIEW

**Comment by BecOzIcan** [comment]
Data not consistent with published AIP 
https://www.transport.gov.ck/wp-content/uploads/2022/01/aip_cookislands_master_12aug21_bkmk.pdf

image


Expected Values

THR08: -21.202583, -159.815708
THR26: -21.202586, -159.795447

**Comment by legoboyvdlp** [comment]
Well, that is not very satisfactory. Why leave a file, that clearly makes the experience worse, since FlightGear will start at an incorrect location?

**Comment by legoboyvdlp** [comment]
I think you are mistaken. 

Your coordinates do not account for the displaced treshold. And my coordinates are correct. 

image

image

**Comment by BecOzIcan** [comment]
The threshold xml file does not reference the end of runway but the actual threshold (from which aircrafts can start accelerating and take off.

Rarotonga does not have displaced thresholds, but only stopways (no effect on the THR coordinates in the file) and the AIP data published is correct. (see below) Not sure where the WED one is sourced from though.

image

**Comment by legoboyvdlp** [comment]
> Not sure where the WED one is sourced from though.
I am happy to move the coordinates west, as it was not clear that it should start from the threshold rather than at the end of the runway. This was caused by an inconsistency between the way that two file formats deal with displaced thresholds. 

Nevertheless; these files _must_ match the scenery. If the airport location is incorrect -- then the correct place to fix it would be in the X-Plane scenery gateway, not in these files.

**Pull request closed without merging**
