### PR TITLE
KSAN_1593810862500

### PR DESCRIPTION
**Pull request by Portree-Kid**
Submitted by pilot.honu4@gmail.com

### CODE REVIEW

**Comment by Honu4** [comment]
I refined the taxilines and attempted to fix pushback holds.

**Comment by BecOzIcan** [comment]
Good work on Pushbacks. Almost to many nodes on runway access curves (not complaining) :-) 


Non BLocking : 
image

Do not include a node here, Aircraft should not Take off or Vacate from here 

image

Routes ending on runway but outside displaced thresholds will not be used 

MERGING

**Comment by Honu4** [comment]
Using flightgear-airports. It doesn't show THR's. I looked at an aerial of the runway and located THR. Is this correct procedure?

Screen Shot 2020-07-04 at 9 20 39 AM

Or perhaps eliminate all extraneous taxilines?

**Comment by Portree-Kid** [comment]
Did you scan/import APT.dat? Otherwise it'd look like this 
image

**Comment by Honu4** [comment]
I appears that the flightgear-airports app needs the FG folder to not be an ".app" folder (Mac) to read all the data. I had originally set it to a regular folder to get the initial scan, then reset to an app folder, inhibiting further reads. Upon resetting to a regular folder, the markings returned. 
I apologize for my lack of knowledge in this matter.
Screen Shot 2020-07-04 at 10 28 54 AM

**Pull request merged**
