### PR TITLE
KCHS_1594752940195

### PR DESCRIPTION
**Pull request by Portree-Kid**
Submitted by wkitty42@gmail.com

### CODE REVIEW

**Comment by BecOzIcan** [comment]
- 100% gates are assigned an airline. No space to accommodate future traffic  

KCHS Travis Err Nowhere to park

- All gates but B2 B4 B6 have invalid pushback holding points. 
http://wiki.flightgear.org/AI_Traffic

**Comment by BecOzIcan** [comment]
Closed without merge

**Comment by wkitty42** [comment]
oh! is that what that means? i had no idea and could only wait and hope that someone would tell me :smile_cat: 

i'll look at the gates again... they passed the check in FGA last time i looked... so B2, B4, and B6 are fine and it is the others that are whack?

[edit]

do all pushback paths have to have a kink/bend in them? interesting...

**Comment by BecOzIcan** [comment]
Pusback validity test does not exist yet. Too many options to look at.

**Comment by wkitty42** [comment]
oh, ok... new file pushed... see ya over there :smile_cat:

**Pull request closed without merging**
