### PR TITLE
New groundnet for EGSS

### PR DESCRIPTION
**Pull request by Portree-Kid**
A new groundnet has been submitted by flightgearairports@example.org.

### CODE REVIEW

**Comment by gooneybird47** [comment]
Hi guys, is there a problem with this file, apart from the fact I forgot to add my name to it?
Brett

**Comment by BecOzIcan** [comment]
It came as "A new groundnet has been submitted by flightgearairports@example.org." so I assumed it was a test only. 

Will merge now.

**Comment by gooneybird47** [comment]
Thanks, I did a clean install of flightgear-airports and forgot to complete the set up.
I'm slowly working on updating my old groundnets in the broken airports list.

**Comment by BecOzIcan** [comment]
Cool. Just make sure the list of Groundnets you ll be working on is in https://github.com/terrasync/main/issues so there is no double up like I just redone LIMC Stefan was already working on

**Pull request merged**
